# Generated by Django 3.2.5 on 2021-08-26 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 5, 33, 23, 747342), verbose_name='date published'),
        ),
    ]
