# Generated by Django 3.2.5 on 2021-08-27 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 17, 4, 7, 355267), verbose_name='date published'),
        ),
    ]
